version: "3"

services:
  postgresql:
    container_name: "postgresql"
    image: postgres
    restart: unless-stopped
    environment:
      "POSTGRES_USER": "admin"
      "POSTGRES_PASSWORD": "admin"
      "POSTGRES_DB": "test"
    ports:
      - 5432:5432
